application: home
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: /home/infinity/google_appengine/home/static
- url: /.*
  script: main.app

libraries:
- name: MySQLdb
  version: latest
- name: webapp2
  version: latest
- name: jinja2
  version: latest
